### ISSUE TITLE
Windowsに直にインストールしたPythonで実行するとエラーがでて起動しない

### ISSUE THREAD

**Issue by takamasa272** [Fukumasu/SectionViewer#2]
# 環境
- Windows 11
- Python 3.11
   - conda等は不使用

```
File "C:\Users\Masaya\AppData\Local\Programs\Python\Python311\Lib\site-packages\sectionviewer\main.py", line 45, in __init__
    ei = [i for i in range(len(path)) if path[i] == 'lib'][0]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
とのエラーが出てしまい，起動しない

**Comment by takamasa272** [comment]
`i for i in range(len(path)) if path[i] == 'lib'` の `lib` が，自分の環境では`Lib`だったため，0番目の要素がないっぽいです．
Libに修正し，Forkして勝手にver1.3.1をつくり，検証したところ，起動しました

**Comment by Fukumasu** [comment]
高橋くん

ご報告ありがとうございます！
大元も修正しました。他のエラーも直してあるので、そちらをお使いください。

引き続きよろしくお願いします。
福益

2023年11月28日(火) 23:18 Masaya Takahashi ***@***.***>:

**Comment by takamasa272** [comment]
ありがとうございます！！
