### ISSUE TITLE
[要望] chの色設定にプリセットの色リストがほしい

### ISSUE THREAD

**Issue by takamasa272** [Fukumasu/SectionViewer#3]
chの表示色を設定する際に，RGBまたはHSLでの数値指定により設定するようになっていると思います（見た限り）

cyan, magenta, green などをよく使うので，そのへんのカラーも含めて，リストで選択もできるようになると嬉しいです．

**Comment by Fukumasu** [comment]
Channelメニューにパレットを追加しました。
1.3.2をご確認ください。

2023年12月6日(水) 2:14 Masaya Takahashi ***@***.***>:

**Comment by takamasa272** [comment]
ご対応ありがとうございます…
めっちゃ速いですね…さすがです…
Updateし，カラーパレットを確認しました．
非常にありがとうございます．助かります．
