### ISSUE TITLE
[Request] add Reset button

### ISSUE THREAD

**Issue by IzukiW** [Fukumasu/SectionViewer#4]
This app is very user-friendly as it can be operated intuitively:)
It would be better if I could return to the default position simply by clicking the 'Reset' button.

**Comment by Fukumasu** [comment]
Thank you for using SectionViewer.
As you suggested, I added ‘Reset pos’ button below the main frame.
Please check ver.1.3.2.

2023年12月6日(水) 4:22 Izuki Watanabe ***@***.***>:

**Comment by IzukiW** [comment]
I have confirmed ‘Reset pos’ button. Thank you for your prompt assistance!
